### PR TITLE
Add a draft pyproject.toml to get dependencies under control

### PR DESCRIPTION
**Pull request by tmolteno**
- [ ] Tests added / passed

  ```bash
  $ py.test --flake8 -v -s .
  ```

  If the flake8 tests fail, the quickest way to correct
  this is to run `autopep8` and then `flake8`
  to fix the remaining issues.

  ```
  $ pip install -U autopep8 flake8
  $ autopep8 -r -i .
  $ flake8 .
  ```

Note there is a failing test. This may be due to dependencies (but it doesn't look good as we needed to upgrade from regions 0.6 due to a numpy >2 requirement for codex-africanus).
```
_______________________________________________ test_regions ________________________________________________

ds9_region_file = '/tmp/pytest-of-tim/pytest-0/test_regions0/region_file.txt'

    def test_regions(ds9_region_file):
        regions = load_regions(ds9_region_file)
    
        c1 = SkyCoord(299.8452923, 40.7403572, frame='fk5', unit='deg')
>       assert regions[0].center.position_angle(c1) == Angle(0, unit='rad')
E       AssertionError: assert <Angle 4.79469185 rad> == <Angle 0. rad>
E        +  where <Angle 4.79469185 rad> = position_angle(<SkyCoord (FK5: equinox=J2000.000): (ra, dec) in deg\n    (299.8452923, 40.7403572)>)
E        +    where position_angle = <SkyCoord (FK5: equinox=J2000.000): (ra, dec) in deg\n    (299.8452923, 40.7403572)>.position_angle
E        +      where <SkyCoord (FK5: equinox=J2000.000): (ra, dec) in deg\n    (299.8452923, 40.7403572)> = <CircleSkyRegion(center=<SkyCoord (FK5: equinox=J2000.000): (ra, dec) in deg\n    (299.8452923, 40.7403572)>, radius=3.751 arcsec)>.center
E        +  and   <Angle 0. rad> = Angle(0, unit='rad')

tests/test_regions.py:11: AssertionError
========================================== short test summary info ==========================================
FAILED tests/test_regions.py::test_regions - AssertionError: assert <Angle 4.79469185 rad> == <Angle 0. rad>
```

### CODE REVIEW

**Comment by sjperkins** [comment]
> Thanks for taking a look at this @tmolteno. The `setup.py` should be removed as `pyproject.toml` replaces it.
> 
> It would be ideal if the cause of the region logic failure could be identified and fixed as relying on old version of `region` isn't great from a maintenance POV.

Actually, we do support > 0.6 in master branch

- https://github.com/caracal-pipeline/crystalball/pull/58

Quite possibly the problem is that we just haven't done a release in a long time (0.4.1 was released in late 2021)

**Comment by tmolteno** [comment]
Been looking into the failing test. Just a regions.read followed by a check of coords. Has regions changed something since 0.6? This is failing in 0.10.

**Comment by tmolteno** [comment]
After playing with poetry, and as far as I can tell, we need to depend on regions > 0.9 because codex-africanus requires numpy > 2 and earlier regions required numpy < 2.

**Comment by sjperkins** [comment]
> Been looking into the failing test. Just a regions.read followed by a check of coords. Has regions changed something since 0.6? This is failing in 0.10.


There was a successful CI run a year ago

https://github.com/caracal-pipeline/crystalball/actions/runs/6794268792/job/18470397210

Unfortunately the logs are gone but the region [releases](https://pypi.org/project/regions/#history) suggests that run succeeded on regions 0.7

**Comment by tmolteno** [comment]
Regions 0.9 added support for Numpy 2.0. https://astropy-regions.readthedocs.io/en/stable/changelog.html

So we need at least regions >= 0.9

**Comment by sjperkins** [comment]
Superceded by #66

**Pull request closed without merging**
